name: MyYml

on: 
   push:
      branches: [ "main" ]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
        
      - uses: actions/checkout@v3
      - name: build 
        run: 
          g++ -o test.exe main.cpp
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         name: main_artifact
         path: test.exe

         retention-days: 4
