name: MyYml

on: 
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: linux-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: build
      run: 
        g++ -o test.exe main.cpp
    
