name: MyYml

on: 
   push:
      branches: [ "main" ]
  
jobs:
  build_docker_and_execute:
      name: Build and execute dockerfile
      runs-on: self-hosted
      
      steps:
      - name: Build docker
        run: |
          $env:DOCKER_HOST="tcp://0.0.0.0:2375"
          docker ps
