name: MyYml

on: 
   push:
      branches: [ "main" ]
  
jobs:
  build_os_matrix:
    name: Build of matrix
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: main
      
    steps:
      - uses: actions/checkout@v3
      - name: Bulding of app 
        run: 
          g++ main.cpp -o main_${{matrix.os}}.exe
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         name: main_matrix
         path: main_${{matrix.os}}.exe
         retention-days: 4      
         
  send_to_telegram:
    needs: build_os_matrix
    name: Send to telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: main_${{matrix.os}}.exe
    
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.app_name }}_${{ matrix.os }}.exe
         
